import React from 'react';

export default function Home() {
  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>Hello Next.js</h1>
      <p>This is a minimal Next.js application generated by ROMA.</p>
    </div>
  );
}
